### ISSUE TITLE
Tracking: Marketing landing pages

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/landing-page#204]
## Overview
To match the current state of the platform and all the new features, we want to update the copy of our existing landing pages for contributors and maintainers, and create new pages for startups and companies.

We want to focus on getting the companies and startups out first, and then update the contributor and maintainer ones.

## Tasks
In order of priority:
- [x] Finalize copy (@chhristopher)
- [ ] Work on graphic assets (@isabensusan)
- [ ] Create new site for companies (@zeucapua )
- [ ] Create new site for startups (@zeucapua )
- [ ] Update the maintainer and contributor sites (@zeucapua )

## Target dates
The goal is to have the companies and startups sites up by the end of the first week of March, and have the other pages updated by the second week of March.

**Comment by bdougie** [comment]
Can we add a site for students as well. We have a planned launch with GitHub Education on March 26th.

Cc @brandonroberts @BekahHW

**Comment by BekahHW** [comment]
@isabensusan does it make sense to break this down into separate issues for what's remaining?

I just noticed that the contributors and maintainers pages haven't been updated.
