### ISSUE TITLE
Feature: Students landing page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/landing-page#222]
### Type of feature

🍕 Feature

### Current behavior

N/A

### Suggested solution

We need to build a landing page for Students, for the upcoming Github Students collaboration.

Due date is March 26th so we need to move fast.

### Tasks

- [x] Copy (@BekahHW @isabensusan @chhristopher)
- [ ] Images (@isabensusan)
- [x] Setup page (@zeucapua)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by BekahHW** [comment]
The copy is done. I tagged @brandonroberts in the doc, but I'll try to grab it after this set of meetings.

**Comment by zeucapua** [comment]
PR is ready to go, with page formatted and linked on the navigation menus. Any changes to copy or images can be made through the Sanity CMS!

**Comment by isabensusan** [comment]
@zeucapua @BekahHW holding off on merging the PR until later today so I can replace the placeholder images with actual images

**Comment by BekahHW** [comment]
@isabensusan just let me know when, so I can send it over to GH with the rest of the resources.
