### ISSUE TITLE
Feature: New enterprise page

### ISSUE THREAD

**Issue by isabensusan** [open-sauced/landing-page#343]
### Suggested solution

We want to build a landing page specifically for Enterprise, since we are looking into focusing on that use case for the time being.

@bdougie's comment:
re: enterprise.
- We have a high level scoped plan [here](https://github.com/open-sauced/api/discussions/930)
- I think the key value is privates repos and inner source.
- The sell is security and compliance.

### Todo

- [ ] Define structure and copy
- [ ] Create assests and design
- [ ] Develop with engineers

**Comment by bdougie** [comment]
Per my DM today. The sell is no longer security and compliance.

It needs governance and policy.
